### PR TITLE
The goal here is to utilize the sprockets tmp/cache/assets cache.

### PR DESCRIPTION
**Pull request by tehsven**
Rails3 never used this cache since turbosprockets always deleted
it when doing a precompile.

So, we create the .parcels_sprockets_workaround directory early
enough so that hike's immutable cache is initially created
with a currect 'stat' entry for files inside this directory.
If this doesn't happen, hike's immutable cache writes an entry
with a 'nil' stat for fortitude files that blows up the second
time you attempt to precompile assets.

Also, we need to ensure that fortitude files are ignored during
initial compilation step. The static compiler doesn't exist
in Rails4 anymore, specifically the method each_logical_path was
moved to base.rb. This behavior was previously handled
inside sprockets.rb monkey patch of ::Sprockets::StaticCompiler
and is now handled by the monkey patch to ::Sprockets::Base.

### CODE REVIEW

**Comment by tehsven** [comment]
I'm testing right now to make sure I didn't break Rails 3.

**Comment by ageweke** [comment]
@tehsven — just refactored out some commonality, and used [`alias_method_chain`](http://apidock.com/rails/ActiveSupport/CoreExtensions/Module/alias_method_chain) (which is now [deprecated in favor of better stuff](http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/), but which Parcels can’t use because it supports older versions of Ruby) — good thing to know about, since it avoids issues just plain `alias_method` can otherwise cause.

If this seems to work (I haven’t tested it — you’re in a much better position to do so since you’re in the thick of this deploy stuff), let me know, and I’ll merge it. Thanks!!

**Comment by ageweke** [comment]
(I wouldn't worry about CI, BTW…it's been so long since I've worked on Travis compatibility that I'm not surprised it's failing. Just see if it works for you. :)

**Comment by tehsven** [comment]
After much investigation, it turns out that I can't use these changes from this repository. I have forked the repo and cherry-picked these changes onto 045c23648c7bdb429d5101942f9b0f0d9e062dd1, which is the only way I got these changes to work correctly. Something happened in the very next commit (4ddde1b168904eb0d9862d12a0bfb2337441df9c) that causes a devise loading error.

**Pull request merged**
